[phases.setup]
nixPkgs = [
  "util-linux",
  "cairo",
  "pango",
  "libjpeg",
  "giflib",
  "librsvg",
  "pkg-config",
  "python3",
  "nodePackages.node-gyp"
]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node index.js"
