[phases.setup]
aptPkgs = [ 
  "uuid-dev",
  "libcairo2-dev",
  "libpango1.0-dev",
  "libjpeg-dev",
  "libgif-dev",
  "librsvg2-dev",
  "pkg-config",
  "python3",
  "python3-pip",
  "build-essential"
]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node index.js"
